version: "3.8"
services:
  store_online:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=OnlineStore
      - MYSQL_ROOT_PASSWORD=MyOnlineStore
    ports:
      - "3306:3306"
volumes:
  db:
    driver: local
