version: "3.8"
services:
  pet_store_3_chang_trai:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=PetStore
      - MYSQL_ROOT_PASSWORD=petstoremaidinh
    ports:
      - "3306:3306"
volumes:
  db:
    driver: local
